package io.nwtn.newton_auth

import org.json.JSONObject
import org.junit.Test
import org.junit.Assert.*
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

@RunWith(RobolectricTestRunner::class)
class JWTUtilsTest {

    @Test
    fun `token decode should be valid`() {
        val decoded = JWTUtils.decode(VALID_TOKEN)
        assertNotNull(decoded)
    }

    @Test
    fun `decoded auth flow state should be valid`() {
        val decoded = JWTUtils.decodeAuthFlowState(VALID_TOKEN)
        assertNotNull("decoding fail", decoded)
        assertEquals(decoded?.loginFlow, AuthFlowState.LoginFlow.normal)
        assertEquals(decoded?.loginStep, AuthFlowState.LoginStep.verifyPhoneCode)
        assertNotNull("no code expires timestamp", decoded?.codeExpiresTimestamp)
        assertNotNull("no code resubmit timestamp", decoded?.codeCanBeResubmittedTimestamp)
        assertEquals(decoded?.codeExpiresTimestamp, 1624001027)
    }

    @Test
    fun `token should be expired`() {
        val expired = JWTUtils.tokenExpired(VALID_TOKEN)
        assertTrue(expired)

    }

}

private const val VALID_TOKEN = """
    eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ6Q2NVS1NRN3JZNkJNSVRWcDFzS09lejJUVE8tcElESGZLWW1EVmlnZEJNIn0.eyJleHAiOjE2MjQwMDEwMjcsImlhdCI6MTYyNDAwMDcyNywianRpIjoiNTM0OThkMTEtZmMxNi00YzBhLTgzNDctZGJlOWIxOGZiN2M2IiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay5uZXd0b24tdGVjaG5vbG9neS5ydS9hdXRoL3JlYWxtcy9zZXJ2aWNlIiwiYXVkIjpbInVzZXJfcmVnaXN0ZXJlZCIsImFjY291bnQiXSwic3ViIjoiKzc5MjIyNzIzNDI3IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoidGV6aXMiLCJzZXNzaW9uX3N0YXRlIjoiMzkxMmIyYjEtODhjYi00ZGE4LTlkODMtZGFiNzBiZjE4ZGVlIiwicGhvbmVfbnVtYmVyIjoiKzc5MjIyNzIzNDI3IiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyIvKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiIiwiY29kZV9jYW5fYmVfcmVzdWJtaXR0ZWRfdGltZXN0YW1wIjoxNjI0MDAwNzg3LCJjb2RlX2V4cGlyZXNfdGltZXN0YW1wIjoxNjI0MDAxMDI3LCJsb2dpbl9zdGVwIjoiVkVSSUZZX1BIT05FX0NPREUiLCJsb2dpbl9mbG93IjoiTk9STUFMIiwibWFza2VkX2VtYWlsIjoibWkqKioqKioqKioqQCoqKioqLioqKiJ9.o7fzcHROum0r8Eina_5GXwkoTNsmGKJ81J8eTRORJ1cwaX8rgyNpeZYgwsJ8ykMmR7HvJ8FRBrwyjd7wORKvB0cw3wWiiLIc71ESB8JFwybIMn7gElQKlZuZYuwP97wKE4feCIS8RiIHTBf7_1jYu96xBi0jruZ3lYJDGHIK4hNA9eUG3fQD9sC1ITh5wwpXHnbRScucQRrcvCqakFd2o_CzqemS8dpKAr2Zhc8SmWkUboW4q0wy6cl_EjQKcZTsrDmaMBpJmKbyuH4NMC6Yp-ms0EU5P3LkvBfdP20LuWSAe7-O2OM2nzSzi_D4ROBo3DyZ-mv2BtSewCyCpAYrbg
"""

private const val NEW_TOKEN = """
    eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ6Q2NVS1NRN3JZNkJNSVRWcDFzS09lejJUVE8tcElESGZLWW1EVmlnZEJNIn0.eyJleHAiOjE2MjMxNzc3NDEsImlhdCI6MTYyMzE3NzQ0MSwianRpIjoiY2E5NTY5NzQtM2MyNS00MDQ0LWFmNGItNTVlYzIwNzYzNTc5IiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay5uZXd0b24tdGVjaG5vbG9neS5ydS9hdXRoL3JlYWxtcy9zZXJ2aWNlIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6InBob25lOis3OTIyMjMzMzMzMyIsInR5cCI6IkJlYXJlciIsImF6cCI6InRlemlzIiwic2Vzc2lvbl9zdGF0ZSI6IjYwZjZjOTk1LTk1OGItNGY2MC1iZTgyLTI3NDIwYWZmYmZlMSIsInBob25lX251bWJlciI6Iis3OTIyMjMzMzMzMyIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiLyoiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6IiIsImxvZ2luX3N0ZXAiOiJWRVJJRllfUEhPTkVfQ09ERSIsImxvZ2luX2Zsb3ciOiJTSE9SVCJ9.ZYTOGT1kz49SFQPrW26U_kITUQRZK-9Z1IPJ1I73KdPCbhKQ2yd-yMBwRuL2hYt1CTKa8kjoWM1mqxEQupXooeqPsrbo5QUpP4iSI6GNR1cQttqoDbMUIedPZjLdQXxsGK97CwY7GEhNEMHjOGnrxT7NCdMvoydrs1_3oPzs0KvJqaiXdX7CetiOI_15fybK7rM5dDJ8E6cg6oGpwNfeLUf49FPpvmKOHeti92I3g13QrTkRxAEQx8RbC8VLvwjNwJlvv-C06reZSaqP7eh-4rqapUZb_TptPBFcl8BeD4w5d3IIxlG784RDb6tccmNfPPJsYNrs1x2GA9tPUFyaIw
"""